language: bash
services: docker

env:
  - VERSION=1.8 PYTHON_VERSION=2.7 PG_MAJOR=9.5 PG_VERSION=9.4+165+deb8u2 VARIANT=slim
  - VERSION=1.8 PYTHON_VERSION=3.5 PG_MAJOR=9.5 PG_VERSION=9.4+165+deb8u2 VARIANT=slim
  - VERSION=1.8 PYTHON_VERSION=2.7 PG_MAJOR=9.5 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.8 PYTHON_VERSION=3.5 PG_MAJOR=9.5 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=9.5 PG_VERSION=9.4+165+deb8u2 VARIANT=slim
  - VERSION=1.9 PYTHON_VERSION=3.5 PG_MAJOR=9.5 PG_VERSION=9.4+165+deb8u2 VARIANT=slim
  - VERSION=1.9 PYTHON_VERSION=2.7 PG_MAJOR=9.5 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.9 PYTHON_VERSION=3.5 PG_MAJOR=9.5 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=9.6 PG_VERSION=9.6+184.pgdg80+1 VARIANT=slim
  - VERSION=1.10 PYTHON_VERSION=3.5 PG_MAJOR=9.6 PG_VERSION=9.6+184.pgdg80+1 VARIANT=slim
  - VERSION=1.10 PYTHON_VERSION=2.7 PG_MAJOR=9.6 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.10 PYTHON_VERSION=3.5 PG_MAJOR=9.6 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=9.6 PG_VERSION=9.6+184.pgdg80+1 VARIANT=slim
  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=9.6 PG_VERSION=9.6+184.pgdg80+1 VARIANT=slim
  - VERSION=1.11 PYTHON_VERSION=2.7 PG_MAJOR=9.6 PG_VERSION=9.5.8-r0 VARIANT=alpine
  - VERSION=1.11 PYTHON_VERSION=3.6 PG_MAJOR=9.6 PG_VERSION=9.5.8-r0 VARIANT=alpine

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-django
      branch: master
