name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        django_version: ["3.2"]
        python_version: ["3.10"]

    env:
      DOCKER_BUILDKIT: 1
      VERSION: ${{ matrix.django_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          QUAY_USER: ${{ secrets.QUAY_IMAGES_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_IMAGES_PASSWORD }}
