name: "Mark stale issues and pull requests"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
            This issue has been automatically marked as stale because it has
            not had recent activity. It will be closed if no further activity
            occurs.
        stale-pr-message: >
            This pull request has been automatically marked as stale because
            it has not had recent activity. It will be closed if no further
            activity occurs.
        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
